ALTER TABLE jobs ALTER COLUMN live_id DROP NOT NULL;

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS crew_id TEXT REFERENCES crews(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_jobs_crew_id ON jobs (crew_id);
