ALTER TABLE crews ADD COLUMN IF NOT EXISTS orchestration_mode TEXT NOT NULL DEFAULT 'router_only';
ALTER TABLE crews ADD COLUMN IF NOT EXISTS llm_config_id TEXT REFERENCES llm_configs(id) ON DELETE SET NULL;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS model_name TEXT NOT NULL DEFAULT 'gpt-5-mini';
